/**
  Generated main.c file from MPLAB Code Configurator

  @Company
    Microchip Technology Inc.

  @File Name
    main.c

  @Summary
    This is the generated main.c using PIC24 / dsPIC33 / PIC32MM MCUs.

  @Description
    This source file provides main entry point for system initialization and application code development.
    Generation Information :
        Product Revision  :  PIC24 / dsPIC33 / PIC32MM MCUs - 1.171.5
        Device            :  PIC24FJ256GA705
    The generated drivers are tested against the following:
        Compiler          :  XC16 v2.10
        MPLAB 	          :  MPLAB X v6.05
*/

/*
    (c) 2020 Microchip Technology Inc. and its subsidiaries. You may use this
    software and any derivatives exclusively with Microchip products.

    THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS". NO WARRANTIES, WHETHER
    EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED
    WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A
    PARTICULAR PURPOSE, OR ITS INTERACTION WITH MICROCHIP PRODUCTS, COMBINATION
    WITH ANY OTHER PRODUCTS, OR USE IN ANY APPLICATION.

    IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE,
    INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND
    WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS
    BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE. TO THE
    FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS IN
    ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF ANY,
    THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.

    MICROCHIP PROVIDES THIS SOFTWARE CONDITIONALLY UPON YOUR ACCEPTANCE OF THESE
    TERMS.
*/

/**
  Section: Included Files
*/
#include "mcc_generated_files/system.h"
#include "mcc_generated_files/uart1.h"  // Include the UART1 header file generated by MCC
#include "mcc_generated_files/pin_manager.h"  // Include the Pin Manager header file

/*
                         Main application
 */
int main(void)
{
    // Initialize the device
    SYSTEM_Initialize();

    // Example messages to send to the receiver
    const char messageOn[] = "LED is ON!\r\n";
    const char messageOff[] = "LED is OFF!\r\n";

    // Configure RA8 as an output
    TRISAbits.TRISA8 = 0;  // Set RA8 as output (0 = output)
    LATAbits.LATA8 = 0;    // Initially turn off the LED (0 = low)

    while (1)
    {
        // Check if data is received
        if (UART1_IsRxReady()) {
            char receivedData = UART1_Read();  // Read received data
            
            // Check if received data is '1'
            if (receivedData == '1') {
                // Turn the LED on
                LATAbits.LATA8 = 1;  // Set the LED high (1 = high)
                
                // Send the message indicating LED is on
                UART1_WriteString(messageOn);
            } 
            // Check if received data is '2'
            else if (receivedData == '2') {
                // Turn the LED off
                LATAbits.LATA8 = 0;  // Set the LED low (0 = low)

                // Send the message indicating LED is off
                UART1_WriteString(messageOff);
            }
            else {
                // Optionally turn the LED off for other received characters
                LATAbits.LATA8 = 0;  // Set the LED low (0 = low)
            }
        }

        // Add other application code here if needed
    }

    return 1;  // Return statement
}

/**
 * Function to send a string via UART
 */
void UART1_WriteString(const char *str)
{
    while (*str) {
        UART1_Write(*str++);  // Send each character until the null terminator
    }
}

/**
 End of File
 */


